### ISSUE TITLE
Issue when editing products per specific store view

### ISSUE THREAD

**Issue by MagefanCustomer** [magefan/magento-2-extended-product-grid#1]
When filtering products by a specific store view we expect the changes made via inline edit to be saved in the specified store view, instead, changes are saved in the default store view.

**System requirements**:  Magento 2.4.2 Community

**Comment by magefan** [comment]
Add the following changes to the **Controller/Adminhtml/Inline/Edit.php** file. 
![image](https://user-images.githubusercontent.com/9151916/178700160-98c8c817-3ee8-4bcf-8a91-0f49988ad85d.png)

The fix will be available in the latest version of the [Magento 2 Extended Product Grid Extension](https://magefan.com/magento-2-product-grid-inline-editor).
